/* eslint-disable no-restricted-globals */

// See https://developers.google.com/web/tools/workbox/modules

import { setCacheNameDetails, clientsClaim } from 'workbox-core'
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import * as googleAnalytics from 'workbox-google-analytics'

const CACHE_PREFIX = 'oc'
const CACHE_SUFFIX = 'v1'

function cacheName(name) {
  return `${CACHE_PREFIX}-${name}-${CACHE_SUFFIX}`
}

setCacheNameDetails({
  prefix: CACHE_PREFIX,
  suffix: CACHE_SUFFIX,
  precache: 'app',
  googleAnalytics: 'analytics'
})

clientsClaim()

googleAnalytics.initialize({
  parameterOverrides: {
    network_status: 'offline'
  }
})

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
const manifest = self.__WB_MANIFEST
// console.log('manifest: %o', manifest)
precacheAndRoute(manifest)

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with the app shell (app.html). Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$')
registerRoute(
  // Return false to exempt requests from being fulfilled by the app shell.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith('/_')) {
      return false
    }

    // If this looks like a URL for a resource, because it contains // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false
    }

    // Return true to signal that we want to use the handler.
    return true
  },
  // app.html: the build's index.html, renamed (vite.config.js).
  createHandlerBoundToURL(`${import.meta.env.BASE_URL}app.html`)
)

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/

const imagesRegEx = /\.(png|jpg|ico|webp)($|\?|#)/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && imagesRegEx.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: cacheName('images')
  })
)
// Files the app downloaded for offline use (saved cenotes' pictures and maps,
// every cave's cover thumbnail - src/services/offline/offlineMedia.js; keep
// these names in sync). Checked before the regular strategies, which would
// otherwise only find files the user happened to view. ignoreVary: Storage
// responses vary on Origin, which the app's own download request and a later
// <img> request needn't match exactly.
const OFFLINE_CACHES = ['oc-offline-saved-caves-v1', 'oc-offline-previews-v1']

// The app's offline downloads themselves (offlineMedia.js fetches them with
// cache: 'no-store' - keep in sync) go straight to the network: they're kept
// in those caches, not also as browsing copies.
const isOfflineDownload = (request) => request.cache === 'no-store'

function preferOfflineCaches(strategy) {
  return async (options) => {
    for (const offlineCacheName of OFFLINE_CACHES) {
      const cached = await caches.match(options.request.url, { cacheName: offlineCacheName, ignoreVary: true })
      if (cached) return cached
    }
    return strategy.handle(options)
  }
}

// Uploaded maps (images/PDFs), fetched through Firebase Storage download
// URLs. (url.origin never has a trailing slash - comparing against one would
// never match.)
registerRoute(
  ({ url, request }) => url.origin === 'https://firebasestorage.googleapis.com' && url.pathname.startsWith('/v0/b/opencaves.appspot.com') && !isOfflineDownload(request),
  preferOfflineCaches(new StaleWhileRevalidate({
    cacheName: cacheName('images')
  }))
)

// Cave pictures and their resized thumbnails, served as public objects from
// the bucket (CaveAsset.js). Each URL's content never changes (uploaded with
// an immutable Cache-Control), so cache-first is safe. The app loads them in
// CORS mode (crossOrigin="anonymous", bucket CORS in storage.cors.json), so
// entries count against quota at their real size. Opaque (status 0)
// responses are still accepted for any <img> without crossOrigin. The cache
// name changed when CORS mode came in, so no earlier opaque entry is ever
// served to a CORS request (which the browser would reject).
registerRoute(
  ({ url, request }) => url.origin === 'https://storage.googleapis.com' && url.pathname.startsWith('/opencaves.appspot.com/') && !isOfflineDownload(request),
  preferOfflineCaches(new CacheFirst({
    cacheName: cacheName('cave-images-cors'),
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 3000, maxAgeSeconds: 90 * 24 * 60 * 60, purgeOnQuotaError: true }),
    ],
  }))
)

// The cave layer (scripts/map-layer/build-tiles.js), for offline use too.
// The offline downloads' copies (saved caves, the Offline setting) are a
// fallback only: they may come from an older build of the layer (tile
// addresses carry no version), so the network and the copies kept while
// browsing come first.
function offlineCachesAsFallback(strategy) {
  return async (options) => {
    try {
      return await strategy.handle(options)
    } catch (error) {
      for (const offlineCacheName of OFFLINE_CACHES) {
        const cached = await caches.match(options.request.url, { cacheName: offlineCacheName })
        if (cached) return cached
      }
      throw error
    }
  }
}


// Its lists (which tiles exist, the maps in them, its build's version):
// fresh when online, their last copy offline.
registerRoute(
  ({ url, request }) => url.origin === self.location.origin && url.pathname.startsWith('/tiles/caves/') && url.pathname.endsWith('.json') && !isOfflineDownload(request),
  offlineCachesAsFallback(new NetworkFirst({ cacheName: cacheName('cave-layer'), networkTimeoutSeconds: 4 }))
)

// Its tiles (and its empty tile): kept as viewed, refreshed in the
// background while online.
registerRoute(
  ({ url, request }) => url.origin === self.location.origin && url.pathname.startsWith('/tiles/caves/') && url.pathname.endsWith('.pbf') && !isOfflineDownload(request),
  offlineCachesAsFallback(new StaleWhileRevalidate({
    cacheName: cacheName('cave-tiles'),
    plugins: [new CacheableResponsePlugin({ statuses: [200] }), new ExpirationPlugin({ maxEntries: 6000, purgeOnQuotaError: true })],
  }))
)

// Caves' addresses (the caveAddress function), kept for offline use.
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.startsWith('/api/address/'),
  new StaleWhileRevalidate({
    cacheName: cacheName('cave-addresses')
  })
)

registerRoute(
  ({ url }) => url.origin === 'https://api.mapbox.com',
  new StaleWhileRevalidate({
    cacheName: cacheName('mapbox-api')
  })
)

registerRoute(
  ({ url }) => url.origin === 'https://www.googletagmanager.com',
  new StaleWhileRevalidate({
    cacheName: cacheName('analytics')
  })
)

// registerRoute(
//   ({ url }) => url.origin === 'https://docs.google.com',
//   new NetworkFirst({
//     cacheName: cacheName('data'),
//     networkTimeoutSeconds: 8
//   })
// )

registerRoute(
  ({ url }) => url.origin === 'https://unpkg.com',
  new CacheFirst({
    cacheName: cacheName('vendors')
  })
)

// Drop the pre-CORS picture cache (opaque entries, replaced by
// cave-images-cors above).
self.addEventListener('activate', (event) => {
  event.waitUntil(caches.delete(cacheName('cave-images')))
})

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// Any other custom service worker logic can go here.
